version: "3"
services:

  postgres:
    container_name: wikijs-postgres
    image: postgres:9
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    container_name: wikijs-app
    image: requarks/wiki:beta
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - frontend
      - backend

  nginx:
    container_name: wikijs-nginx
    image: nginx:1.17
    depends_on:
      - wiki
    networks:
      - frontend
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/private
    ports:
      - "80:80"
      - "443:443"

volumes:
  db-data:

networks:
  frontend:
  backend: