version: "3"
services:

  db:
    image: postgres:9-alpine
    container_name: wikijs-postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  wiki:
    image: requarks/wiki:beta
    container_name: wikijs-app
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx
    container_name: wikijs-nginx
    depends_on:
      - wiki
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certs:/etc/ssl/private

volumes:
  db-data: